### PR TITLE
add papers in later 2023

### PR DESCRIPTION
**Pull request by naoto0804**
Thank you for initiating a great project!
I would like to include several papers that have appeared recently.

### CODE REVIEW

**Comment by JosephKJ** [comment]
Dear @naoto0804, many thanks for the PR, and your amazing works in this space! Your works like FlexDM really inspires us.

**Comment by JosephKJ** [comment]
Please allow me to add you as a collaborator to this repo :)

**Comment by naoto0804** [comment]
Glad to hear that! Let's make this niche area move forward;

**Comment by JosephKJ** [comment]
Absolutely!

**Pull request merged**
